### ISSUE TITLE
php with utf-8 tokenization are broken

### ISSUE THREAD

**Issue by Savier** [github/CodeSearchNet#106]
I've tried to use php_dedupe_definitions_v2.pkl for my own project and found many functions with broken tokenization. For example, find functions with empty ('') tokens - there are above 8000 of that. Then, If we try to look for all 1-letter tokens we will get tons of 1-letter utf8 tokens which is impossible.

**Comment by hamelsmu** [comment]
Thanks savier, perhaps the `code` field can be used instead of the `code_tokens` field so you can do your own tokenization in the meantime?  Thank you for letting us know about this issue!
