### ISSUE TITLE
about

### ISSUE THREAD

**Issue by direction-yuan** [github/CodeSearchNet#115]
use train set and valid set for training
and codebase for evaluating the model
so test set for what?
deep code search says that manual evaluation,
there is way for auto evaluation?

and for java dataset   some desc is empty  and some desc is not english ,like german

**Comment by hamelsmu** [comment]
@direction-yuan perhaps this paper will help clarify things.  Let us know if there are additional questions

https://arxiv.org/pdf/1909.09436.pdf
