### ISSUE TITLE
Can I download the models?

### ISSUE THREAD

**Issue by edmondfrancoismillionnaires** [github/CodeSearchNet#124]
Hello!
Is there a way to download the models without having to do the training ?
If not, can someone share his training ?
Thank you very much !

**Comment by hamelsmu** [comment]
Yes you can, from Weights & Biases

@staceysv is there some instructions that I should link to on this?

**Comment by hamelsmu** [comment]
@staceb friendly ping

**Comment by hamelsmu** [comment]
The models are available from the leaderboard.  You download our models here:

- nueral-bag-of-words: https://app.wandb.ai/github/codesearchnet/runs/5lzp82bu/files
- 1dcnn: https://app.wandb.ai/github/codesearchnet/runs/g9yrby1i/files
- self-attention: https://app.wandb.ai/github/codesearchnet/runs/h6vbduxb/files
- rnn: https://app.wandb.ai/github/codesearchnet/runs/a8yfarln/files

Thanks!

**Comment by postatum** [comment]
Hi @hamelsmu.
Can I use these models to make predictions?
If so, can you, please, share a tip on how to use these models?
