### ISSUE TITLE
Preprocessing of docstrings can be improved

### ISSUE THREAD

**Issue by villmow** [github/CodeSearchNet#128]
Hello, 

first thanks for the challenge, the code and the dataset! Really cool stuff that you're doing and I want to work on this task. :)

I've read the Contribution Guidelines and know that you will not change any of the preprocessing code, but nevertheless I want to discuss the preprocessing of the docstrings here in case someone wants to produce a similar dataset (or maybe v3 ;) ) . 

### Current preprocessing of docstrings

I read your code and it seems that this is the way you preprocess the docstrings:

 1. You extract the documentation from the method and strip c-style delimiters https://github.com/github/CodeSearchNet/blob/9356b3181eaa9d4a38df4d309018158fd23448cb/function_parser/function_parser/parsers/commentutils.py#L1
 2. Then you extract the relevant part of the docstring (which acts as a summary) using the following heuristics:
  2.1 If `\n\n` is found you take the part before
  2.2 otherwise take the part before the first `@`
  2.3. otherwise take the full docstring  https://github.com/github/CodeSearchNet/blob/9356b3181eaa9d4a38df4d309018158fd23448cb/function_parser/function_parser/parsers/commentutils.py#L18-L24
 3. Finally you tokenize the extracted summary using the following regex:
https://github.com/github/CodeSearchNet/blob/9356b3181eaa9d4a38df4d309018158fd23448cb/function_parser/function_parser/parsers/language_parser.py#L5

### Problems with this pipeline

This way of preprocessing produces a couple of results that are probably not wanted and could be improved.

#### Extracting the summary

Compare the first 12 lines of the tokenized docstrings of the **java** train set to the raw ones
```markdown
Bind indexed elements to the supplied collection .
Set {
Add {
Set servlet names that the filter will be registered against . This will replace any previously specified servlet names .
Add servlet names for the filter .
Set the URL patterns that the filter will be registered against . This will replace any previously specified URL patterns .
Add URL patterns as defined in the Servlet specification that the filter will be registered against .
Convenience method to {
Configure registration settings . Subclasses can override this method to perform additional configuration if required .
Create a nested {
Create a nested {
Create a nested {
```
As you can see 6/12 are basically not usable.

```markdown
**Bind indexed elements to the supplied collection.** @param name the name of the property to bind @param target the target bindable @param elementBinder the binder to use for elements @param aggregateType the aggregate type, may be a collection or an array @param elementType the element type @param result the destination for results
**Set** {@link **ServletRegistrationBean**}**s that the filter will be registered against.** @param servletRegistrationBeans the Servlet registration beans
**Add** {@link **ServletRegistrationBean**}**s for the filter.** @param servletRegistrationBeans the servlet registration beans to add @see #setServletRegistrationBeans
**Set servlet names that the filter will be registered against. This will replace any previously specified servlet names.** @param servletNames the servlet names @see #setServletRegistrationBeans @see #setUrlPatterns
**Add servlet names for the filter.** @param servletNames the servlet names to add
**Set the URL patterns that the filter will be registered against. This will replace any previously specified URL patterns.** @param urlPatterns the URL patterns @see #setServletRegistrationBeans @see #setServletNames
**Add URL patterns, as defined in the Servlet specification, that the filter will be registered against.** @param urlPatterns the URL patterns
**Convenience method to** {@link **#setDispatcherTypes(EnumSet) set dispatcher types**} **using the specified elements.** @param first the first dispatcher type @param rest additional dispatcher types
**Configure registration settings. Subclasses can override this method to perform additional configuration if required.** @param registration the registration
**Create a nested** {@link **DependencyCustomizer**} **that only applies if any of the specified class names are not on the class path.** @param classNames the class names to test @return a nested {@link DependencyCustomizer}
**Create a nested** {@link **DependencyCustomizer**} **that only applies if all of the specified class names are not on the class path.** @param classNames the class names to test @return a nested {@link DependencyCustomizer}
**Create a nested** {@link **DependencyCustomizer**} **that only applies if the specified paths are on the class path.** @param paths the paths to test @return a nested {@link DependencyCustomizer}
```
However, the relevant information is in the raw docstrings (I added the ** to highlight relevant passages). Simply using the part before the first `@` produces pretty bad results (at least in java) as its common practice to highlight code blocks or links with javadoc-tags. 
**Possible solution:** Stripping everything before the first `param` (or maybe `@param`) and afterwards removing javadoc-tags (maybe keeping the tokens inside).

#### Cleaning 
The preprocessing does not include any cleaning. This manifests in docstrings that contain html-tags (which are commonly found in javadoc), as well as URLs (which afterwards get pretty verbose tokenized). See these two samples from **java**
```
Determine if a uri is in origin - form according to <a href = https : // tools . ietf . org / html / rfc7230#section - 5 . 3 > rfc7230 5 . 3< / a > .
Determine if a uri is in asterisk - form according to <a href = https : // tools . ietf . org / html / rfc7230#section - 5 . 3 > rfc7230 5 . 3< / a > .
```

Some stats
```bash
>>> wc -l java.train.comment 
454436 java.train.comment
>>> grep -E '<p >|<p >' java.train.comment | wc -l
42750
```
At least 10% of the tokenized java docstrings still contain html tags. 
```bash
>>> grep '{ @' java.train.comment | wc -l
44500
```
Another 10% still contain javadoc.
```bash
>>> grep "{ @inheritDoc }" java.train.comment | wc -l
1685
```
2k consist only of a single javadoc-tag indication that the doc was inherited. 

Many of the **golang** docstrings contain URLs, which are not very useful in the tokenized version the regex produces (see above in java).
```bash
>>> wc -l go.train.comment 
317822 go.train.comment
>>> grep -E 'http :|https :' go.train.comment | wc -l
19753
```
~6% contain URLs (starting with `http :`)

```bash
>>> grep -E "autogenerated|auto generated" go.train.comment | wc -l
4850
```
Around 5k auto generated methods

```bash
>>> grep "/ *" go.train.comment | wc -l
33620
```
10% still contain c-style comment delimiters.

#### Tokenization

Any specific reason you keep punctuation symbols like `.`, `,`, `-`, `/`, `:`, `<`, `>`, `*`, `=`, `@`, `(`, `)` as tokens? Is it to keep code in the docstrings?   

### Summary
I really think better cleaning and a language-dependent preprocessing would produce higher quality docstrings At least for `java` a removal of javadoc and html could be beneficial.  As well as using everything before the first `param`  as  a summary  (maybe in combination with the first paragraph `\n\n` heuristic).

**Comment by hamelsmu** [comment]
Thanks for the feature request and suggestions.  This project is currently in maintenance mode, but we are happy to take a pull request. 

Thanks

**Comment by Ceceu** [comment]
> maintenance mode
Yet in maintenance mode? What kind of improvements can we expect?

**Comment by hamelsmu** [comment]
No improvements.  This project is no longer being maintained

**Comment by Ceceu** [comment]
> No improvements. This project is no longer being maintained

Ok. Then, what about publishing the relevance judgment used to calculate NDCG?

**Comment by skye95git** [comment]
> Hello,
> 
> first thanks for the challenge, the code and the dataset! Really cool stuff that you're doing and I want to work on this task. :)
> 
> I've read the Contribution Guidelines and know that you will not change any of the preprocessing code, but nevertheless I want to discuss the preprocessing of the docstrings here in case someone wants to produce a similar dataset (or maybe v3 ;) ) .
> 
> ### Current preprocessing of docstrings
> I read your code and it seems that this is the way you preprocess the docstrings:
> 
> 1. You extract the documentation from the method and strip c-style delimiters https://github.com/github/CodeSearchNet/blob/9356b3181eaa9d4a38df4d309018158fd23448cb/function_parser/function_parser/parsers/commentutils.py#L1
> 2. Then you extract the relevant part of the docstring (which acts as a summary) using the following heuristics:
>    2.1 If `\n\n` is found you take the part before
>    2.2 otherwise take the part before the first `@`
>    2.3. otherwise take the full docstring  https://github.com/github/CodeSearchNet/blob/9356b3181eaa9d4a38df4d309018158fd23448cb/function_parser/function_parser/parsers/commentutils.py#L18-L24
> 3. Finally you tokenize the extracted summary using the following regex:
>    https://github.com/github/CodeSearchNet/blob/9356b3181eaa9d4a38df4d309018158fd23448cb/function_parser/function_parser/parsers/language_parser.py#L5
> 
> ### Problems with this pipeline
> This way of preprocessing produces a couple of results that are probably not wanted and could be improved.
> 
> #### Extracting the summary
> Compare the first 12 lines of the tokenized docstrings of the **java** train set to the raw ones
> 
> ```gfm
> Bind indexed elements to the supplied collection .
> Set {
> Add {
> Set servlet names that the filter will be registered against . This will replace any previously specified servlet names .
> Add servlet names for the filter .
> Set the URL patterns that the filter will be registered against . This will replace any previously specified URL patterns .
> Add URL patterns as defined in the Servlet specification that the filter will be registered against .
> Convenience method to {
> Configure registration settings . Subclasses can override this method to perform additional configuration if required .
> Create a nested {
> Create a nested {
> Create a nested {
> ```
> 
> As you can see 6/12 are basically not usable.
> 
> ```gfm
> **Bind indexed elements to the supplied collection.** @param name the name of the property to bind @param target the target bindable @param elementBinder the binder to use for elements @param aggregateType the aggregate type, may be a collection or an array @param elementType the element type @param result the destination for results
> **Set** {@link **ServletRegistrationBean**}**s that the filter will be registered against.** @param servletRegistrationBeans the Servlet registration beans
> **Add** {@link **ServletRegistrationBean**}**s for the filter.** @param servletRegistrationBeans the servlet registration beans to add @see #setServletRegistrationBeans
> **Set servlet names that the filter will be registered against. This will replace any previously specified servlet names.** @param servletNames the servlet names @see #setServletRegistrationBeans @see #setUrlPatterns
> **Add servlet names for the filter.** @param servletNames the servlet names to add
> **Set the URL patterns that the filter will be registered against. This will replace any previously specified URL patterns.** @param urlPatterns the URL patterns @see #setServletRegistrationBeans @see #setServletNames
> **Add URL patterns, as defined in the Servlet specification, that the filter will be registered against.** @param urlPatterns the URL patterns
> **Convenience method to** {@link **#setDispatcherTypes(EnumSet) set dispatcher types**} **using the specified elements.** @param first the first dispatcher type @param rest additional dispatcher types
> **Configure registration settings. Subclasses can override this method to perform additional configuration if required.** @param registration the registration
> **Create a nested** {@link **DependencyCustomizer**} **that only applies if any of the specified class names are not on the class path.** @param classNames the class names to test @return a nested {@link DependencyCustomizer}
> **Create a nested** {@link **DependencyCustomizer**} **that only applies if all of the specified class names are not on the class path.** @param classNames the class names to test @return a nested {@link DependencyCustomizer}
> **Create a nested** {@link **DependencyCustomizer**} **that only applies if the specified paths are on the class path.** @param paths the paths to test @return a nested {@link DependencyCustomizer}
> ```
> 
> However, the relevant information is in the raw docstrings (I added the ** to highlight relevant passages). Simply using the part before the first `@` produces pretty bad results (at least in java) as its common practice to highlight code blocks or links with javadoc-tags.
> **Possible solution:** Stripping everything before the first `param` (or maybe `@param`) and afterwards removing javadoc-tags (maybe keeping the tokens inside).
> 
> #### Cleaning
> The preprocessing does not include any cleaning. This manifests in docstrings that contain html-tags (which are commonly found in javadoc), as well as URLs (which afterwards get pretty verbose tokenized). See these two samples from **java**
> 
> ```
> Determine if a uri is in origin - form according to <a href = https : // tools . ietf . org / html / rfc7230#section - 5 . 3 > rfc7230 5 . 3< / a > .
> Determine if a uri is in asterisk - form according to <a href = https : // tools . ietf . org / html / rfc7230#section - 5 . 3 > rfc7230 5 . 3< / a > .
> ```
> 
> Some stats
> 
> ```shell
> >>> wc -l java.train.comment 
> 454436 java.train.comment
> >>> grep -E '<p >|<p >' java.train.comment | wc -l
> 42750
> ```
> 
> At least 10% of the tokenized java docstrings still contain html tags.
> 
> ```shell
> >>> grep '{ @' java.train.comment | wc -l
> 44500
> ```
> 
> Another 10% still contain javadoc.
> 
> ```shell
> >>> grep "{ @inheritDoc }" java.train.comment | wc -l
> 1685
> ```
> 
> 2k consist only of a single javadoc-tag indication that the doc was inherited.
> 
> Many of the **golang** docstrings contain URLs, which are not very useful in the tokenized version the regex produces (see above in java).
> 
> ```shell
> >>> wc -l go.train.comment 
> 317822 go.train.comment
> >>> grep -E 'http :|https :' go.train.comment | wc -l
> 19753
> ```
> 
> ~6% contain URLs (starting with `http :`)
> 
> ```shell
> >>> grep -E "autogenerated|auto generated" go.train.comment | wc -l
> 4850
> ```
> 
> Around 5k auto generated methods
> 
> ```shell
> >>> grep "/ *" go.train.comment | wc -l
> 33620
> ```
> 
> 10% still contain c-style comment delimiters.
> 
> #### Tokenization
> Any specific reason you keep punctuation symbols like `.`, `,`, `-`, `/`, `:`, `<`, `>`, `*`, `=`, `@`, `(`, `)` as tokens? Is it to keep code in the docstrings?
> 
> ### Summary
> I really think better cleaning and a language-dependent preprocessing would produce higher quality docstrings At least for `java` a removal of javadoc and html could be beneficial. As well as using everything before the first `param` as a summary (maybe in combination with the first paragraph `\n\n` heuristic).

Have you improved the preprocessing of docstrings？Can you share the url？
