### ISSUE TITLE
question: changing the default leaderboard order 

### ISSUE THREAD

**Issue by monperrus** [github/CodeSearchNet#129]
The default ordering on the [leaderboard](https://app.wandb.ai/github/codesearchnet/benchmark/leaderboard) is "Mean NDCG" over all results that are not `None`.

This means it is very easy to appear \#1 by overfitting on a single language.

What about computing "Mean NDCG" over all 6 languages and replacing `None` by `0`?

**Comment by hamelsmu** [comment]
@staceysv Can you help with this?

**Comment by hamelsmu** [comment]
@staceysv @nbardy  can you help with this issue?

**Comment by hamelsmu** [comment]
Closing this issue as it has become stale

**Comment by monperrus** [comment]
Ack. I understand that the default leaderboard order will stay the same.

**Comment by hamelsmu** [comment]
@cvphelps can you look into this questino re: leaderboard ?

**Comment by hamelsmu** [comment]
This competition has now concluded
