### ISSUE TITLE
W&B Default Screen - Wasted Real Estate

### ISSUE THREAD

**Issue by hamelsmu** [github/CodeSearchNet#13]
Consider opening the Auto-Visualizations by default, right now - when you navigate to a project it opens with the below view.  Seems like wasted real-estate

![image](https://user-images.githubusercontent.com/1483922/65440762-179aa600-ddde-11e9-944a-830b713c0195.png)

**Comment by staceysv** [comment]
moving this to relevant wandb issue tracker -- thanks!
