### ISSUE TITLE
CodeChallenge run prediction on whole code corpus?

### ISSUE THREAD

**Issue by yss14** [github/CodeSearchNet#132]
Did I get it right, that for a submission on the challenge, I have to run those 99 queries against the whole code corpus, and not just the test set?
Thanks in advance :)

**Comment by yss14** [comment]
And if so, is it safe to use the provided `{lang}_dedupe_definitions_v2.pkl` for my already trained custom model to run predictions (like you do in [predict.py](https://github.com/github/CodeSearchNet/blob/master/src/predict.py))? Or do I have to aggregate all content from the jsonline files?

**Comment by mallamanis** [comment]
Hi @yss14 
Yes, for each of the 99 queries, the challenge is to retrieve the most relevant functions in the whole code corpus. You should feel free to use any data you want to train any model (the test data is "hidden" behind the leaderboard).

This commonly means that you'd need to ask your trained model to rank the snippets for each programming language and for each query.

**Comment by yss14** [comment]
@mallamanis Thanks for your answer.
Do you have any clue how to efficently read the 6.6GB large `javascript_dedupe_definitions_v2.pkl` file? On my machine with 16GB RAM python takes 90% memory before the process is shut down due to memory limits.
`pickle.load(open('/home/yss/Downloads/javascript_dedupe_definitions_v2.pkl', 'rb'))`

**Comment by mallamanis** [comment]
@yss14 you're right that this is a constraint we hadn't forseen.

We could easily convert the `.pkl` to a `.jsonl.gz` that can be read-in efficiently (e.g. with [`load_jsonl_gz`](https://github.com/microsoft/dpu-utils/blob/master/python/dpu_utils/utils/dataloading.py#L22)) by iterating though each sample. Do you think that this would be useful? Let us know if that'd be useful, and I can see how we can upload this somewhere.

**Comment by yss14** [comment]
@mallamanis I now did it by myself, but I think for other people a jsonl file might be useful :)
