### ISSUE TITLE
wandb custom submission error

### ISSUE THREAD

**Issue by yss14** [github/CodeSearchNet#133]
I'm currently trying to submit a custom model. After entering the run, evaluating the ndcg score, and writing a brief note on how we approached the results, I get the following error

![wandb_submission_error](https://user-images.githubusercontent.com/4346842/79581548-d3992680-80ca-11ea-8d0b-1201877ab559.png)

Now, when I click `refresh`, I will be redirected to the submission page again. When trying to re-submit, I get the following error `Invalid CSV format. Please upload a well-formatted CSV file.`.

**Comment by Zamony** [comment]
I have the same problem too. Have you found a solution?

**Comment by hamelsmu** [comment]
@shawnlewis ☝️ can you take a look?

**Comment by novoselrok** [comment]
I get this error too after submitting model predictions.

**Comment by hamelsmu** [comment]
@cvphelps can you help?

**Comment by nbardy** [comment]
@novoselrok @yss14 We just shipped a fix which should fix your issues with submission.

I want to make sure your submissions are received, please respond here if there are additional issues. Or optionally to me directly via email: nick@wandb.com

**Comment by novoselrok** [comment]
@nbardy It seems to be working now. I managed to submit this run: https://app.wandb.ai/roknovosel/glorified-code-search/runs/21hzzq1h/overview and a PR was opened: https://github.com/github/CodeSearchNet/pull/159 (I'm glad it worked on my best submission yet :smile:)
