### ISSUE TITLE
How long does it usually take to review a run?

### ISSUE THREAD

**Issue by novoselrok** [github/CodeSearchNet#136]
Hi!

I've made a custom model and now I'm trying to submit it to the leaderboard. Here is the run: https://app.wandb.ai/github/codesearchnet/runs/lqqo1i4m

Above it says 'Awaiting review from codesearchnet benchmark' and that's probably the reason why I get an error when I try to 'Publish to GitHub'. Am I doing something wrong, or do I just have to wait?

Thanks.

**Comment by hamelsmu** [comment]
I believe it has been reviewed now, please let us know if there are any issues.

**Comment by novoselrok** [comment]
Issue is still present, I get the same error. I even created a new WANDB project and the same thing happens again. On both projects it still says 'Awaiting review from codesearchnet benchmark'. I have a fork of this repository, so I'm not sure what the problem is.

![Zaslonska slika_2020-05-03_08-50-08](https://user-images.githubusercontent.com/6417322/80907940-69fc5780-8d1b-11ea-8df6-448c6724fa5a.png)
![Zaslonska slika_2020-05-03_08-50-37](https://user-images.githubusercontent.com/6417322/80907942-6b2d8480-8d1b-11ea-9388-5088a8370a92.png)

**Comment by hamelsmu** [comment]
Can you take a screenshot of the error or the awaiting review screen?

Can you email support@wandb.com as well just linking to this issue?

**Comment by novoselrok** [comment]
Thanks @hamelsmu, I've sent them an email.

**Comment by hamelsmu** [comment]
Could this issue be a duplicate of #133 ?  If so would prefer to track in a single issue

**Comment by novoselrok** [comment]
It probably is, I'll close this one.
