### ISSUE TITLE
W&B When You Tag A Run, Doesn't Appear Until Refresh

### ISSUE THREAD

**Issue by hamelsmu** [github/CodeSearchNet#14]
See animation below, perhaps something is broken in javascript

![label_problem](https://user-images.githubusercontent.com/1483922/65441103-b1625300-ddde-11e9-8aa9-2707070530a6.gif)

I do get the following error in the console: `Error while trying to use the following icon from the Manifest: https://app.wandb.ai/favicon.png (Resource size is not correct - typo in the Manifest?)`

**Comment by staceysv** [comment]
this is already tracked in Weights & Biases -- thanks!
