### ISSUE TITLE
Error while processing a single Python file.

### ISSUE THREAD

**Issue by vikrant-sahu** [github/CodeSearchNet#193]
In CodeSearchNet/function_parser/function_parser/demo.ipynb .  I kept everything same till thrid cell and then I did this `processor.process_single_file(py_file_path)` . Here `py_file_path` contains the complete path of .py file that I want to process. 

After executing the above line I got the following error :
`unhashable type: 'tree_sitter.Node'`  in file `function_parser/function_parser/parsers/language_parser.py`.  

Am I missing something?

**Comment by Ceceu** [comment]
Hello @vikrant-sahu,
Did you find a solution?

**Comment by hamelsmu** [comment]
We are no longer maintaining this project See announcement in the README

**Comment by vikrant-sahu** [comment]
@Ceceu yes. I break down the code to make it work. 
Will publish it in a few weeks.

**Comment by HaorenD** [comment]
> @Ceceu yes. I break down the code to make it work.
> Will publish it in a few weeks.

Hello, i met the same problem now. I use the lateset version docker file. Could u pls share how u fix it or share the code?

**Comment by skye95git** [comment]
> @Ceceu yes. I break down the code to make it work.
> Will publish it in a few weeks.

Hi, I meet the same problem with you. Where did you publish it?
