### ISSUE TITLE
How to custom model submissions?

### ISSUE THREAD

**Issue by yss14** [github/CodeSearchNet#211]
How do I submit custom models only containing a `model_predictions.csv` file as an output of the custom model? It seems like the CI tests fail on custom model submissions and thus the PR is closed (see https://github.com/github/CodeSearchNet/pull/184)?

**Comment by mallamanis** [comment]
Hi @yss14 

There must have been an issue with the check and a miscommunication from our part on your submission. Everything looked okay in #184, which is now merged. Feel free to make new submissions!
