### ISSUE TITLE
999 distractor snippets

### ISSUE THREAD

**Issue by ncshrikanth** [github/CodeSearchNet#214]
Thank You for CodeSearchNet. A quick question: if we wish to replicate Table 3 (of your paper) where can we find the 999 distractor snippets and how did you form those 999 snippets?

**Comment by Zamony** [comment]
Hi, @ncshrikanth!
As far as I can tell, they were generated randomly:
https://github.com/github/CodeSearchNet/blob/e792e1caea20fbd4fba439565fe20c10d4798435/src/model_test.py#L58

**Comment by ncshrikanth** [comment]
I see, thanks @Zamony !
