### ISSUE TITLE
Support Dart and Flutter

### ISSUE THREAD

**Issue by Marken23** [github/CodeSearchNet#224]
Flutter is a UI DSL currently pushed by Google. It uses the Dart programming language.

Is there any chance that you create Dart and Flutter dataset just like java, python, php, go, js and ruby?

Thanks for your work!

**Comment by mallamanis** [comment]
Hi @Marken23,

We do not have any future plans regarding CodeSearchNet or collecting new data/annotations. However, if someone collects a relevant dataset, I would be happy to add a link next to our dataset of annotations in the README file.
