### ISSUE TITLE
Generating Pypi module for function_parser

### ISSUE THREAD

**Issue by ncoop57** [github/CodeSearchNet#227]
Hi, 

Are there any plans to export the function_parser library this repo has into a proper pypi module people could easily install? It looks awesome and I bet a ton of SE people could make use of it, especially if it was made a bit easier to setup. I'm more than happy to help with generating a PR to do it and if need be helping finishing any final touches it needs (I understand how research tools sometimes be :)).

 BTW, love the research and uploading all your data and code. I've used it numerous times in my research 🤓.

**Comment by mallamanis** [comment]
Hi @ncoop57 ,

I am glad that you have found this work useful! We don't have any plans to extract the function parser into a standalone package. However, the code is licensed under MIT, so you should feel free to clone/copy-paste the relevant code and create a PyPI package that you and others can use.

**Comment by ncoop57** [comment]
Already have 🤓 (https://github.com/ncoop57/function_parser) and have been using it for one of my research projects! Thank you to you and your team for a really useful tool 😀

**Comment by mallamanis** [comment]
Great to hear! Added a relevant notice in the corresponding folder https://github.com/github/CodeSearchNet/commit/76a006fda591591f196fd0aef1d6282af3135f71
