### ISSUE TITLE
downloads of pretrained baseline models

### ISSUE THREAD

**Issue by alext234** [github/CodeSearchNet#41]
Is there a link where we can download pretrained baseline models ?

**Comment by hamelsmu** [comment]
You can head over to Weights & Biases and you will find the model artifacts there:

1. Go to the [leaderboard](https://app.wandb.ai/github/CodeSearchNet/benchmark/leaderboard)

2. Select a run

3. from left-hand panel select files

4. you will see model files there

**Comment by alext234** [comment]
Thanks @hamelsmu 
I've seen some `pkl.gz` - should be the pickled models.
