### ISSUE TITLE
Extract descriptions from `@return` doc comments if method has no summary?

### ISSUE THREAD

**Issue by TysonAndre** [github/CodeSearchNet#44]
e.g. some short methods may contain a description in the return tag, but not a description of the method itself. (to avoid redundancy).

Doing this would extract more methods, but they may be of lower quality if incorrectly parsed or automatically generated. I'd expect a description such as `@return bool STARTDESCRIPTION true if this is a float` to be extracted (I'm not familiar with how the data representation works)

- Some libraries/applications are strict about always having a summary in their coding standards, others aren't.
- e.g. I've seen `@return the description` without a type for php
- Could try to annotate the fact that the fallback was used and this is a non-official summary

```php
    /**
     * @return bool true if this is a float
     */
    public function isFloat()
```

It would be nice to account for code such as `@return HasTemplate<string, stdClass>`, etc. Making sure that `<([{` in the first token are matched up may be useful as a basic approach (and give up if that fails). (There's no official standard and different static analyzers have their own extensions to the type syntax)

An example implementation for PHP is https://github.com/phan/phan/blob/2.2.12/src/Phan/Language/Element/MarkupDescription.php - examples of what it generates as descriptions are https://github.com/phan/phan/blob/2.2.12/tests/Phan/Language/Element/MarkupDescriptionTest.php#L132-L155

**Comment by hamelsmu** [comment]
@TysonAndre thanks again for your helpful insight.  For reasons discussed in https://github.com/github/CodeSearchNet/pull/46 we are not making changes regarding improvements to the model or preprocessing to this repository but are really interested in your results if you try this out yourself benchmarks might look like. 

I suspect you might beat the benchmarks for PHP :)

**Comment by TysonAndre** [comment]
Thanks for the reply. I suppose [CONTRIBUTING](https://github.com/github/CodeSearchNet/blob/master/CONTRIBUTING.md#scope) could be clearer about what parts of the code accept minor improvements unless it's on a case-by-case basis. Something along the below lines:

> Therefore, we are accepting pull requests for the following items:
> 
> - Bug fixes
> - Updates to documentation, including links to your project(s) where improvements to the baseline have been made
> - **Minor improvements to the code** *(generally excluding changes regarding improvements to the model or preprocessing to this repository - file an issue to discuss ideas)*

**Comment by hamelsmu** [comment]
@TysonAndre Thank you very much for your thoughtful suggestion.  I apologize that our CONTRIBUTING.md was not clearer and I apologize.  Thanks for bringing this to our attention -- I'll make an ammendment right now.  

Thanks again for contributing to this project!  We really appreciate it!

**Comment by hamelsmu** [comment]
@TysonAndre we amended our CONTRIBUTING to allow for these kinds of changes, now.  We have to setup better CI/CD etc. to allow for these contributions so we may be slow to merge these kinds of things in the interim

**Comment by hamelsmu** [comment]
@TysonAndre you are welcome to try to make a PR with these changes if you are so inclined.  We have amended our CONTRIBUTING rules to allow for these changes

**Comment by hamelsmu** [comment]
Please feel free to submit a PR to fix ... closing this issue as it has become stale
