### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by rudolfolah** [github/CodeSearchNet#48]
Just wanted to leave a note of appreciation. I've been looking for parsers that would deconstruct code into tokens easily (specifically for Ruby code, I took at look at [parser](https://github.com/whitequark/parser) which is just an AST and would have required more processing) so that I could figure out potential call sites and relations between test files and source code.

I'm looking to prioritize tests that should be run based on which functions are added/removed/updated, similar to what's found in the paper [*The art of testing less without sacrificing quality*](https://dl.acm.org/citation.cfm?id=2818815).

**Comment by hamelsmu** [comment]
Thanks @rudolfolah, The real super heroes in this situation are the @github/semantic-code team (@dcreager @aymannadeem @tclem @joshvera @maxbrunsfeld @patrickt @rewinfrey @robrix)  

You should check out this project that they recently open-sourced as it may be really useful for what you want to do!  https://github.com/github/semantic

Thank you for the kind note 🙇

**Comment by tclem** [comment]
> I'm looking to prioritize tests that should be run based on which functions are added/removed/updated

Nice! Semantic does syntax aware diffs which might be just the thing for ☝️. Check out the [examples](https://github.com/github/semantic/blob/master/docs/examples.md#diffs).
