### ISSUE TITLE
The function processor.process_single_file() fail to output.

### ISSUE THREAD

**Issue by chenqiuyuan** [github/CodeSearchNet#56]
Hi, I want to use the parser to process my own data. First I want to try several single files, but the function  `processor.process_single_file()` fails to output things (just an empty list). How can I debug? I have used the provided docker to set up my environment.

**Comment by hamelsmu** [comment]
Can you provide the exact commands etc that we can use to try to reproduce this issue?

**Comment by chenqiuyuan** [comment]
Hi, thanks for the response！ I just followed the readme and executed `script/bootstrap` and `script/console`. Then I find that `script/setup` will download a very large file (12 GB). So I skipped it and tried to use the `parser_cli` (which call `processor.process_single_file()`) to parse several local single files but fail. 

However, I have targeted the problem. Today I read the source code and found that the command is designed for the online github project. So could you provide functions that can parse local files? just a command like `python parse.py --language xxx input_file_directory out_put_directory` is very nice. I wanted to do it myself but found the inner data structure is too complex for me to handle.

**Comment by hamelsmu** [comment]
Hi @chenqiuyuan -- unfortunately we do not have the bandwidth to extend the functionality of the tools provided to parse local files with the interface you are looking for.  It should be something you can do by modifying the code contained in this repo slightly.  

Sorry about that, please let us know if you end up making anything cool with this data!
