### ISSUE TITLE
Standalone model_predictions.csv

### ISSUE THREAD

**Issue by Ceceu** [github/CodeSearchNet#66]
How to submit only `model_predictions.csv` file from an external project?

**Comment by hamelsmu** [comment]
@Ceceu did you read [these instructions](https://github.com/github/CodeSearchNet/blob/master/BENCHMARK.md#submitting-runs-to-the-benchmark)  ?  If so, please let us know if some part of that is not clear.  What step you are stuck on exactly, etc.

**Comment by Ceceu** [comment]
Following the instructions in [submitting model predictions to W&B](https://github.com/github/CodeSearchNet/blob/master/BENCHMARK.md#submitting-model-predictions-to-wb), I generated `model_predictions.csv` as a result of the [submission format](https://github.com/github/CodeSearchNet/blob/master/BENCHMARK.md#submission-format). I performed steps 1 and 2 without being logged in to W&B. From here, is it still possible to send only `model_predictions.csv` for verification purposes?

**Comment by hamelsmu** [comment]
See my comments in https://github.com/github/CodeSearchNet/issues/67

we can continue the discussion there.  🙇 Thanks!
