### ISSUE TITLE
A minor Java tokenization utf-related issue

### ISSUE THREAD

**Issue by bzz** [github/CodeSearchNet#83]
This may not be something very important or worth fixing immediately, but there may be a small bug in Java function tokenization.

At least one [function](https://github.com/jbehave/jbehave-core/blob/bdd6a6199528df3c35087e72d4644870655b23e6/examples/i18n/src/main/java/org/jbehave/examples/trader/i18n/steps/DeSteps.java#L22-L25) in the dataset has `code_tokens` that do not include a `{` token.

-----

Quick inspection with
```python
with pd.option_context('display.max_colwidth', -1):
    display(jdf.loc[jdf['url'] == 'https://github.com/jbehave/jbehave-core/blob/bdd6a6199528df3c35087e72d4644870655b23e6/examples/i18n/src/main/java/org/jbehave/examples/trader/i18n/steps/DeSteps.java#L22-L25'][['code', 'code_tokens']])
```

shows tokens like `tring , ymbol` for this code

```java
@Given("ich habe eine Aktion mit dem Symbol $sümbol und eine Schwelle von $threshold")
public void aStock(@Named("sümbol") String symbol, @Named("threshold") double threshold) { ...
```

`code_tokens` looks like this

```
[@, Given, (, "ich habe eine Aktion mit dem Symbol  𝑠ü𝑚𝑏𝑜𝑙𝑢𝑛𝑑𝑒𝑖𝑛𝑒𝑆𝑐ℎ𝑤𝑒𝑙𝑙𝑒𝑣𝑜𝑛 threshold"), , public, void, aStock, (, @, Named, (, "sümbol"), , tring , ymbol,, , N, amed(, ", threshold"), ...]
```

I'm not very familiar with the extraction pipeline codebase, but the fact that [tree-sitter](https://tree-sitter.github.io/tree-sitter/playground) seems to identify the locations well
<img width="692" alt="Screen Shot 2019-10-27 at 2 52 10 PM" src="https://user-images.githubusercontent.com/5582506/67635600-6948bb80-f8c9-11e9-9c5f-b314f3de6103.png"> makes me think that [JavaParser.get_definition()](https://github.com/github/CodeSearchNet/blob/c2e14d409eebe24cc635727ffda8ab3065317e44/function_parser/function_parser/parsers/java_parser.py#L14), that is doing some index math, may be worth closer inspection.

**Comment by hamelsmu** [comment]
@mallamanis I am not that familiar with the Java tokenizer, is this something you understand more?

**Comment by bzz** [comment]
One more example that may not be related, but if it is, would make me think about possibility of some off-by-one rather than a UTF 🐞 . Will be happy to move it to a separate issue as well.

Here is a [java function](https://github.com/spring-projects/spring-boot/blob/0b27f7c70e164b2b1a96477f1d9c1acba56790c1/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/condition/BeanTypeRegistry.java#L96-L101) who's `code`, `url` and `code_tokens` miss the last line with the closing `}` and thus making it a bit annoying to parse.

<details>
 <summary>Steps to reproduce</summary>

```python
with pd.option_context('display.max_colwidth', -1):
    display(df[df.code.str.contains("getNamesForType")][["url", "code", "code_tokens"]])
```

And again, tree-sitter seems to identify the location of the end of the block just fine
<img width="696" alt="Screen Shot 2019-10-30 at 6 58 32 PM" src="https://user-images.githubusercontent.com/5582506/67885203-6d820c80-fb47-11e9-9cac-9dc081f136a4.png">

</details>

Thanks again for the great work putting it all together and the prompt reply, from my side I'll also try to find some time to dig deeper into this.
