### ISSUE TITLE
tokens_str in Encoder

### ISSUE THREAD

**Issue by sjakati98** [github/CodeSearchNet#95]
I have been trying to implement a "custom" encoder within this codebase, and I was wondering how to get access to the raw tokens (in string form). 

What I have tried so far:

* Setting up the `tokens_str` placeholder:
```python
self.placeholders['tokens_str'] = \
            tf.placeholder(tf.string,
                           shape=[None, self.get_hyper('max_num_tokens')],
                           name='tokens_str')
```

Once I have those, I am trying to pipe the tokens into the tf_hub Elmo module, as follows:
```python
seq_tokens = self.placeholders['tokens_str']
seq_tokens_lengths = self.placeholders['tokens_lengths']
            
# ## DEBUGGING: OUTPUT SHAPES
# print("Sequence Tokens Shape: %s" % seq_tokens.shape)
# print("Sequence Tokens Lengths: %s" % seq_tokens_lengths)

## pull elmo model from tensorflow hub
elmo = hub.Module("https://tfhub.dev/google/elmo/2", trainable=is_train)
token_embeddings = elmo(
     {
           "tokens": seq_tokens,
           "sequence_len": seq_tokens_lengths
      },
     signature='tokens',
    as_dict=True
)['elmo'] ## [batch_size, max_length, 1024 or 512]
```

I can see from my debugging statements, that `seq_tokens` shape is `(?, 200)`, which is expected and `seq_tokens_lengths` shape is `(?)` which is also expected.

The error I get is `len(seq_lens) != input.dims(0), (1000 vs. 0)`, which is coming from the ELMo model. But I'm guessing that this is coming from the `seq_tokens` not being pushed into the ELMo model. 
Any help is appreciated!

**Comment by mallamanis** [comment]
HI @sjakati98,
The code doesn't support using the string representation of tokens as-is. 

I believe that you need to create a new `Encoder` for your use-case. Specifically, [`load_data_from_sample`](https://github.com/github/CodeSearchNet/blob/master/src/encoders/encoder.py#L137) is the function that's invoked for converting a raw sample (as it appears in the `.jsonl`) into a format that is "understood" by the network. Then [`extend_minibatch_by_sample`](https://github.com/github/CodeSearchNet/blob/master/src/encoders/encoder.py#L175) takes care of the minibatching logic.

By implementing a custom `Encoder`, you should be able to use the pre-built ELMo model in an encoder; it'd be interesting to see the results :)
